dist: trusty
sudo: required
language: bash
before_script:
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
before_script:
- echo "Preparation...."
- sudo apt update && sudo apt install python gcc python-pip libssl-dev libffi-dev
- pip install --user ansible && pip install --user ansible-lint && pip install --user cryptography==2.2.2
- echo "Terraform installation"
- wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip -O /tmp/terraform.zip
- sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
- touch /home/travis/.ssh/appuser.pub && touch /home/travis/.ssh/appuser
- echo "TFlint installation"
- wget https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_amd64.zip -O /tmp/tflint.zip
- sudo unzip -d /usr/local/bin/ /tmp/tflint.zip
script:
- echo "Packer templates validation"
- cp packer/variables.json.example packer/variables.json && find packer -regextype posix-egrep -regex ".*/(app|db)\.json" -type f -print0 | xargs -0 -n1 packer validate -var-file=packer/variables.json
- echo "Terraform config validation"
- cp terraform/stage/terraform.tfvars.example terraform/stage/terraform.tfvars && terraform init -backend=false terraform/stage && terraform validate -var-file terraform/stage/terraform.tfvars terraform/stage
- cp terraform/prod/terraform.tfvars.example terraform/prod/terraform.tfvars && terraform init -backend=false terraform/prod && terraform validate -var-file terraform/prod/terraform.tfvars terraform/prod
- echo "Tflint validation"
- tflint terraform/stage/*.tf --var-file=terraform/stage/terraform.tfvars
- tflint terraform/prod/*.tf --var-file=terraform/prod/terraform.tfvars
- echo "Ansible playbooks validation"
- find ansible/playbooks -name *.yml -type f -print0 | xargs -0 -n1 ansible-lint
- echo "Check for a badge in README.md"
- grep "\[\!\[Build Status\](https://.*)\](https://.*)" README.md
notifications:
  slack:
    rooms:
      secure: bT4kjqyYtBv9phRnah2TtA0lwnjUgY/ul2wZdDuvKxNLuPJPy5htA8IsbucX/vKYCG/dAif0nsqJTfCnhMtOQHKtZm6l4gfJJcOihdW2CmG+1WREwXTX/MVH9UsheWB9++drjMGLbTHHIyshX8mMeya4xjH2J/VsS9c+wArUCv489KmWFvW+newYuZYyXH8yipuZrwA5tOIKMWP0fnhaTis90fan5x/YAmM75TMvrJYekakm5+pEZ2ol+4hL39k5dnfZLfttZfaUtgOFzaULTdTqgwqhzkGk507nBMQ6pYWXgjcCBCPKZf8whTW7YlvW1yBCjCDjBG1XdoYcZInHh+u8u35aqN0Ck2nFlpEKbNCjmwzEqkHSS5vuZ3J1WY94Nbk0I7IvLb3HMXBjym3qPProgyU7qxtAARzTl2yCPYn2FNpO20X7KhhnzV4ekCrPLizbVl0sDwPNOP1voIvJzDhmQmx4xymMRg07lUnFXtvUT+nSy3F5pJXvHFL2ycn3TjD0P+yj+LhuEgAYzUPqdeh+D8gt1oetCGNf0BnL8SnWoi8XJVJoiQv0xStC02ROK1NdwSjnHV/fmUddACPymZneMUkyZgSlh4ywLMKs2mG8KrWNMwazADQ5XBchqXkGpbMKBHQ49ZqzXXMRy9lnMCUCjlDBvzG+6WsoOhPWsHA=

